CPPSRC = main.cpp Game.cpp GraphicObject.cpp Texture.cpp Note.cpp ObjectManager.cpp Timer.cpp SoundBuffer.cpp Sound.cpp SoundManager.cpp ConfReader.cpp
HSRC = settings.h Game.h GraphicObject.h Texture.h Note.h ObjectManager.h Timer.h SoundBuffer.h Sound.h SoundManager.h ConfReader.h
OBJ = $(CPPSRC:.cpp=.o)
